import pygame

# 从 settings.json 加载所有配置
# 为了保持向后兼容，所有常量从 config.py 导入
try:
    from config import (
        # 游戏配置
        SCREEN_WIDTH,
        SCREEN_HEIGHT,
        FPS,
        PLAYER_SPEED,
        PLAYER_ROTATION_SPEED,
        ROTATE_CAMERA,
        CAMERA_FOLLOW_LERP,
        MOUSE_TURN_SPEED,
        MOUSE_TURN_DEADZONE,
        AIMING_SPEED_MULTIPLIER,
        BULLET_SPEED,
        BULLET_COOLDOWN,
        RELOAD_TIME,
        MAGAZINE_SIZE,
        PLAYER_RADIUS,
        BULLET_RADIUS,
        BULLET_DAMAGE,
        RESPAWN_TIME,
        RESPAWN_PROTECTION,
        # 地图配置
        MAP_TYPE,
        ROOM_SIZE,
        WALL_THICKNESS,
        DOOR_SIZE,
        DOOR_ANIMATION_SPEED,
        DOOR_OPEN_ANGLE,
        DOOR_PUSH_ACCEL,
        DOOR_DAMPING,
        DOOR_MAX_SPEED,
        DOOR_GRAB_DISTANCE,
        DOOR_SELF_CLOSE_ANGLE,
        DOOR_SELF_CLOSE_SPEED,
        DOOR_SELF_CLOSE_VELOCITY,
        # 效果配置
        HIT_SLOWDOWN_DURATION,
        HIT_SLOWDOWN_FACTOR,
        # 近战配置
        MELEE_DAMAGE,
        MELEE_RANGE,
        MELEE_COOLDOWN,
        MELEE_ANIMATION_TIME,
        MELEE_ANGLE,
        HEAVY_MELEE_DAMAGE,
        HEAVY_MELEE_RANGE,
        HEAVY_MELEE_COOLDOWN,
        HEAVY_MELEE_ANIMATION_TIME,
        HEAVY_MELEE_ANGLE,
        # 瞄准配置
        AIM_CAMERA_RANGE,
        AIM_SENSITIVITY,
        AIM_OFFSET_LERP,
        # 网络配置
        SERVER_PORT,
        MAX_PLAYERS,
        BUFFER_SIZE,
        HEARTBEAT_INTERVAL,
        CLIENT_TIMEOUT,
        CONNECTION_TIMEOUT,
        SCAN_TIMEOUT,
        # 视角配置
        FIELD_OF_VIEW,
        VISION_RANGE,
        AIMED_FIELD_OF_VIEW,
        # 聊天配置
        MAX_CHAT_MESSAGES,
        CHAT_DISPLAY_TIME,
        MAX_CHAT_LENGTH,
        # AI配置
        USE_ENHANCED_AI,
        AI_COST_UPDATE_INTERVAL,
        COMMANDS_PREFIX,
        COMMANDS_ENABLED,
        # 颜色
        WHITE,
        RED,
        GREEN,
        BLUE,
        BLACK,
        GRAY,
        DARK_GRAY,
        LIGHT_GRAY,
        VISION_GROUND,
        YELLOW,
        DOOR_COLOR,
        DARK_DOOR_COLOR,
        DEAD_COLOR,
        VISION_COLOR,
        FOG_COLOR,
        LIGHT_GRAY_TRANSPARENT,
        LIGHT_BLUE,
        DARK_BLUE,
        ORANGE,
        PURPLE,
        MELEE_COLOR,
        MELEE_RANGE_COLOR,
        AIM_COLOR,
        # 道具配置
        ITEMS_ENABLED,
        ITEMS_SPAWN_COUNT,
        ITEMS_RESPAWN_ENABLED,
        ITEMS_PICKUP_RANGE,
        ITEM_HEALTH_PACK_ENABLED,
        ITEM_AMMO_BOX_ENABLED,
        ITEM_ARMOR_ENABLED,
        ITEM_SPEED_BOOST_ENABLED,
        ITEM_DAMAGE_BOOST_ENABLED,
        ITEM_GRENADE_ENABLED,
        ITEM_HEALTH_PACK_HEAL,
        ITEM_HEALTH_PACK_RESPAWN,
        ITEM_AMMO_BOX_AMMO,
        ITEM_AMMO_BOX_RESPAWN,
        ITEM_ARMOR_AMOUNT,
        ITEM_ARMOR_REDUCTION,
        ITEM_ARMOR_RESPAWN,
        ITEM_SPEED_BOOST_DURATION,
        ITEM_SPEED_BOOST_MULTIPLIER,
        ITEM_SPEED_BOOST_RESPAWN,
        ITEM_DAMAGE_BOOST_DURATION,
        ITEM_DAMAGE_BOOST_MULTIPLIER,
        ITEM_DAMAGE_BOOST_RESPAWN,
        ITEM_GRENADE_DAMAGE,
        ITEM_GRENADE_RADIUS,
        ITEM_GRENADE_RESPAWN,
        ITEM_GRENADE_THROW_SPEED,
        ITEM_GRENADE_FUSE_TIME,
        ITEM_GRENADE_FRICTION,
        ITEM_GRENADE_BOUNCE_DAMPING,
        ITEM_HEALTH_PACK_WEIGHT,
        ITEM_AMMO_BOX_WEIGHT,
        ITEM_ARMOR_WEIGHT,
        ITEM_SPEED_BOOST_WEIGHT,
        ITEM_DAMAGE_BOOST_WEIGHT,
        ITEM_GRENADE_WEIGHT,
    )
except ImportError:
    # 如果 config.py 导入失败，使用默认值（用于首次导入）
    # 游戏配置
    SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
    FPS = 60
    PLAYER_SPEED = 300
    PLAYER_ROTATION_SPEED = 180
    ROTATE_CAMERA = True
    CAMERA_FOLLOW_LERP = 0.18
    MOUSE_TURN_SPEED = 180
    MOUSE_TURN_DEADZONE = 0.2
    AIMING_SPEED_MULTIPLIER = 0.5
    BULLET_SPEED = 800
    BULLET_COOLDOWN = 0.15
    RELOAD_TIME = 2.0
    MAGAZINE_SIZE = 30
    PLAYER_RADIUS = 20
    BULLET_RADIUS = 5
    BULLET_DAMAGE = 20
    RESPAWN_TIME = 3.0
    RESPAWN_PROTECTION = 2.0

    # 地图配置
    MAP_TYPE = "grid3x3"
    ROOM_SIZE = 600
    WALL_THICKNESS = 20
    DOOR_SIZE = 80
    DOOR_ANIMATION_SPEED = 2.0
    DOOR_OPEN_ANGLE = 150.0
    DOOR_PUSH_ACCEL = 18.0
    DOOR_DAMPING = 0.6
    DOOR_MAX_SPEED = 6.0
    DOOR_GRAB_DISTANCE = 110
    DOOR_SELF_CLOSE_ANGLE = 5.0
    DOOR_SELF_CLOSE_SPEED = 16.0
    DOOR_SELF_CLOSE_VELOCITY = 0.2

    # 效果配置
    HIT_SLOWDOWN_DURATION = 0.5
    HIT_SLOWDOWN_FACTOR = 0.5

    # 近战配置
    MELEE_DAMAGE = 40
    MELEE_RANGE = 60
    MELEE_COOLDOWN = 0.8
    MELEE_ANIMATION_TIME = 0.3
    MELEE_ANGLE = 90
    HEAVY_MELEE_DAMAGE = 60
    HEAVY_MELEE_RANGE = 45
    HEAVY_MELEE_COOLDOWN = 1.2
    HEAVY_MELEE_ANIMATION_TIME = 0.45
    HEAVY_MELEE_ANGLE = 60

    # 瞄准配置
    AIM_CAMERA_RANGE = 400
    AIM_SENSITIVITY = 1
    AIM_OFFSET_LERP = 0.25

    # 网络配置
    SERVER_PORT = 5555
    MAX_PLAYERS = 10
    BUFFER_SIZE = 65536
    HEARTBEAT_INTERVAL = 1.0
    CLIENT_TIMEOUT = 5.0
    CONNECTION_TIMEOUT = 10.0
    SCAN_TIMEOUT = 1.0

    # 视角配置
    FIELD_OF_VIEW = 120
    VISION_RANGE = 300

    # 聊天配置
    MAX_CHAT_MESSAGES = 10
    CHAT_DISPLAY_TIME = 10.0
    MAX_CHAT_LENGTH = 50

    # AI配置
    USE_ENHANCED_AI = True
    AI_COST_UPDATE_INTERVAL = 0.25
    COMMANDS_PREFIX = "."
    COMMANDS_ENABLED = True

    # 颜色
    WHITE = (255, 255, 255)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    BLUE = (0, 0, 255)
    BLACK = (0, 0, 0)
    GRAY = (100, 100, 100)
    DARK_GRAY = (50, 50, 50)
    LIGHT_GRAY = (140, 140, 140)
    VISION_GROUND = (80, 80, 80)
    YELLOW = (255, 255, 0)
    DOOR_COLOR = (139, 69, 19)
    DARK_DOOR_COLOR = (69, 34, 9)
    DEAD_COLOR = (128, 128, 128)
    VISION_COLOR = (255, 255, 0, 30)
    FOG_COLOR = (20, 20, 20, 180)
    LIGHT_GRAY_TRANSPARENT = (200, 200, 200, 80)
    LIGHT_BLUE = (173, 216, 230)
    DARK_BLUE = (0, 100, 200)
    ORANGE = (255, 165, 0)
    PURPLE = (128, 0, 128)
    MELEE_COLOR = (255, 100, 100)
    MELEE_RANGE_COLOR = (255, 0, 0, 80)
    AIM_COLOR = (0, 255, 255)

    # 道具配置
    ITEMS_ENABLED = True
    ITEMS_SPAWN_COUNT = 12
    ITEMS_RESPAWN_ENABLED = True
    ITEMS_PICKUP_RANGE = 35
    ITEM_HEALTH_PACK_ENABLED = True
    ITEM_AMMO_BOX_ENABLED = True
    ITEM_ARMOR_ENABLED = True
    ITEM_SPEED_BOOST_ENABLED = True
    ITEM_DAMAGE_BOOST_ENABLED = True
    ITEM_GRENADE_ENABLED = True
    ITEM_HEALTH_PACK_HEAL = 50
    ITEM_HEALTH_PACK_RESPAWN = 30
    ITEM_AMMO_BOX_AMMO = 30
    ITEM_AMMO_BOX_RESPAWN = 25
    ITEM_ARMOR_AMOUNT = 50
    ITEM_ARMOR_REDUCTION = 0.5
    ITEM_ARMOR_RESPAWN = 35
    ITEM_SPEED_BOOST_DURATION = 10
    ITEM_SPEED_BOOST_MULTIPLIER = 1.5
    ITEM_SPEED_BOOST_RESPAWN = 20
    ITEM_DAMAGE_BOOST_DURATION = 15
    ITEM_DAMAGE_BOOST_MULTIPLIER = 1.5
    ITEM_DAMAGE_BOOST_RESPAWN = 25
    ITEM_GRENADE_DAMAGE = 80
    ITEM_GRENADE_RADIUS = 140
    ITEM_GRENADE_RESPAWN = 40
    ITEM_GRENADE_THROW_SPEED = 400
    ITEM_GRENADE_FUSE_TIME = 3.0
    ITEM_GRENADE_FRICTION = 1.2
    ITEM_GRENADE_BOUNCE_DAMPING = 0.6
    ITEM_HEALTH_PACK_WEIGHT = 0.35
    ITEM_AMMO_BOX_WEIGHT = 0.25
    ITEM_ARMOR_WEIGHT = 0.15
    ITEM_SPEED_BOOST_WEIGHT = 0.10
    ITEM_DAMAGE_BOOST_WEIGHT = 0.10
    ITEM_GRENADE_WEIGHT = 0.15
